// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBXzMAt8NJGOmqcSAS61qi6clVzTGu7g',
    appId: '1:713977023293:web:10fd5b045bfa3e67819354',
    messagingSenderId: '713977023293',
    projectId: 'dju-berry-iot-8140',
    authDomain: 'dju-berry-iot-8140.firebaseapp.com',
    storageBucket: 'dju-berry-iot-8140.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuVZ1-Ugem5kHBhg2TEEGaX1PxxJBHaI',
    appId: '1:713977023293:android:aa22206ad0193d3c819354',
    messagingSenderId: '713977023293',
    projectId: 'dju-berry-iot-8140',
    storageBucket: 'dju-berry-iot-8140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKvYBtIKfBILcHPmDxk_-gvrBDQ_l94Q',
    appId: '1:713977023293:ios:9c8b163a7a654a21819354',
    messagingSenderId: '713977023293',
    projectId: 'dju-berry-iot-8140',
    storageBucket: 'dju-berry-iot-8140.appspot.com',
    iosBundleId: 'com.example.iotProjectBerry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKvYBtIKfBILcHPmDxk_-gvrBDQ_l94Q',
    appId: '1:713977023293:ios:9c8b163a7a654a21819354',
    messagingSenderId: '713977023293',
    projectId: 'dju-berry-iot-8140',
    storageBucket: 'dju-berry-iot-8140.appspot.com',
    iosBundleId: 'com.example.iotProjectBerry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBXzMAt8NJGOmqcSAS61qi6clVzTGu7g',
    appId: '1:713977023293:web:147d199d0394d6d9819354',
    messagingSenderId: '713977023293',
    projectId: 'dju-berry-iot-8140',
    authDomain: 'dju-berry-iot-8140.firebaseapp.com',
    storageBucket: 'dju-berry-iot-8140.appspot.com',
  );
}
